upgrade gems by `$ bundle update`
Occured errors:

- NoMethodError: undefined method `validate' for #<User> (thus changed to #valid? instead)
- NoMethodError: undefined method `deliver_now' for #<Mail::Message> (so changed back to #delever)